global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'service-status-exporter'
    static_configs:
      - targets: ['monitor:8000']
remote_write:
  - url: "${REMOTE_WRITE_URL}"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "service_status"
        action: "keep"
