{
 "title": "General Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Global Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "service_status{service=\"global\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZKSync Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max without (timestamp) (\n  service_status{service=\"zksync\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZKSync WebSocket Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max without (timestamp) (\n  service_status{service=\"zksync-websocket\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}